CREATE TABLE IF NOT EXISTS STUDENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    JMBAG VARCHAR(255),
    ECTS INTEGER,
    BIRTH_DATE DATE
    );

CREATE TABLE IF NOT EXISTS COURSE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    ECTS INTEGER
    );

CREATE TABLE IF NOT EXISTS STUDENT_COURSE (
    STUDENT_ID BIGINT,
    COURSE_ID BIGINT,
    PRIMARY KEY (STUDENT_ID, COURSE_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
    );
